version: '3.9'

volumes:
  code:
  node-modules:
  db-store:
  music:
    driver: local
  search_index:
    driver: local

x-mutagen:
  sync:
    code:
      alpha: '.'
      beta: 'volume://code'
      mode: 'two-way-resolved'
      ignore:
        vcs: true
      permissions:
        defaultFileMode: 0666
        defaultDirectoryMode: 0777
      configurationBeta:
        permissions:
          defaultOwner: id:0
          defaultGroup: id:0

services:
  web:
    image: nginx:latest
    depends_on:
      - app
    networks:
      - default
      - docker_default
    volumes:
      - music:/music
      - code:/code
      - ./docker/nginx/conf.d/local.d/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.koel.rule=Host(`koel.localhost`)'
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    tty: true
    volumes:
      - music:/music
      - search_index:/code/storage/search-indexes
      - code:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - js
      - db
    labels:
      - 'traefik.enable=false'
  js:
    build:
      context: .
      dockerfile: ./docker/js/Dockerfile
    tty: true
    volumes:
      - code:/code
      - node-modules:/code/node_modules
    labels:
      - 'traefik.enable=false'
  db:
    image: mysql:8.0.32
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/0.sql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    labels:
      - 'traefik.enable=false'
networks:
  default: {}
  docker_default:
    name: docker_default
